# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

default_platform(:android)


# ------------- BUILD WITH LOCAL AND BITRISE ------------------- #
# Ex: fastlane ld_deploy flavor_type:internal build_type:releaselocal update:patch
platform :android do

  ADMITTED_BUMP = ["major", "minor", "patch"]
  ADMITTED_FLAVOR = ["internal", "closed", "open"]
  ADMITTED_BUILDTYPE = ["release", "releaselocal"]

  desc "Clean, increment version/name, build, deploy and submit a new testflight version"
  lane :ld_deploy do |options|

    flavor_type = options[:flavor_type]
    build_type = options[:build_type]

    check_flavor(
      flavor_type: flavor_type
    )

    check_build_type(
      build_type: build_type
    )

    clean()

    version_name = incrementvb(
      update: options[:update],
      flavor_type: flavor_type
    )

    build_and_deploy(
      flavor_type: flavor_type,
      build_type: build_type,
      version_name: version_name
    )

    commit_and_push()
  end


  lane :check_flavor do |options|
    flavor_type = options[:flavor_type]
    if flavor_type == nil
      UI.user_error!("'flavor_type' parameter not present")
      # UI.important "Skipping build because a cached build is available!"
      # next # skip doing the rest of this lane
    end

    if !ADMITTED_FLAVOR.include?(flavor_type)
      UI.user_error!("'" + flavor_type + "' must be one of: 'internal', 'closed', 'open'")
    end
    UI.message("Build type present and correct: #{flavor_type}")
  end


  lane :check_build_type do |options|
    build_type = options[:build_type]
    if build_type == nil
      UI.user_error!("'build_type' parameter not present")
    end

    if !ADMITTED_BUILDTYPE.include?(build_type)
      UI.user_error!("'" + build_type + "' must be one of: 'release', 'releaselocal'")
    end
    UI.message("Build type present and correct: #{build_type}")
  end


  lane :clean do
    gradle(task: 'clean')
    UI.message("Gradle clean success")
  end

  
  lane :incrementvb do |options|

    to_update = options[:update]
    flavor_type = options[:flavor_type]

    if to_update == nil
      UI.user_error!("'update' parameter not present")
    end

    if !ADMITTED_BUMP.include?(to_update)
      UI.user_error!("'" + to_update + "' must be one of: 'minor', 'major', 'patch'")
    end
    UI.message("to_update present and correct: #{to_update}")

    # Increment version
    version_name = increment_version_name(
      app_project_dir: '**/app',
      bump_type: to_update,
      flavor: flavor_type
    )
    UI.message("New version name: #{version_name}")

    version_code = increment_version_code(app_project_dir: '**/app', flavor: flavor_type)
    UI.message("New version code: #{version_code}")
    version_name
  end


  lane :build_and_deploy do |options|
    flavor_type = options[:flavor_type]
    build_type = options[:build_type]
    gradle(
      # task: 'assemble',
      task: 'bundle',
      flavor: flavor_type,
      build_type: build_type,     
      print_command: false
    )
    UI.message("Gradle bundle succeded")

    version_name = options[:version_name]
    upload_to_play_store(
      track: flavor_type,
      release_status: 'draft',
      version_name: version_name
    )
    UI.message("Deploy succesfull")
  end


  lane :commit_and_push do
    git_commit(path: ".", message: "Version Bump")
    UI.message("Commit done")

    push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "master",  # optional, aliased by "branch", default is set to current branch
      remote_branch: "master"
    )
    UI.message("Branch updated")
  end


  # ---------------------------- TESTING -----------------------------

  lane :testbuild do
    gradle(task: 'clean')
    UI.message("Gradle clean success")

    gradle(
      # task: 'assemble',
      task: 'bundle',
      flavor: 'internal',
      build_type: 'releaselocal',     
      print_command: false,
      flags: '--stacktrace'
    )
    UI.message("Gradle bundle succeded")
  end


  lane :show_version do
    # Default
    version = get_version_name(app_project_dir: '**/app')
    UI.message("Default: #{version}")
    version_code = get_version_code(app_project_dir: '**/app')
    UI.message("Default: #{version_code}")

    # Demo
    version_demo = get_version_name(
      app_project_dir: '**/app',
      flavor: 'demo'
    )
    UI.message("demo flavor: #{version_demo}")
    version_code_demo = get_version_code(
      app_project_dir: '**/app',
      flavor: 'demo'
    )
    UI.message("demo flavor: #{version_code_demo}")

    # Qa
    version_qa = get_version_name(
      app_project_dir: '**/app',
      flavor: 'qa'
    )
    UI.message("qa flavor: #{version_qa}")
    version_code_qa = get_version_code(
      app_project_dir: '**/app',
      flavor: 'qa'
    )
    UI.message("qa flavor: #{version_code_qa}")
  end


  #major minor patch build
  lane :bumpup do
    # Default
    increment_version_name(app_project_dir: '**/app', bump_type: 'patch')
    increment_version_code(app_project_dir: '**/app')

    # internal
    increment_version_name(
      app_project_dir: '**/app',
      bump_type: 'minor',
      flavor: 'internal'
    )
    increment_version_code(app_project_dir: '**/app', flavor: "internal")

    # #Qa
    # increment_version_name(
    #   app_project_dir: '**/app',
    #   bump_type: 'patch',
    #   flavor: 'internal'
    # )
    # increment_version_code(app_project_dir: '**/app', flavor: "internal")

    # commit()
  end

  # Ex: fastlane incrementtest update:patch
  lane :incrementtest do |options|

    to_update = options[:update]

    if to_update == nil
      UI.user_error!("'update' parameter not present")
    end

    if !ADMITTED_BUMP.include?(to_update)
      UI.user_error!("'" + to_update + "' must be one of: 'minor', 'major', 'patch'")
    end

    if to_update == "major"
      index = 0
    elsif to_update == "minor"
      index = 1
    else # patch
      index = 2
    end

    cur_build = get_version_name(
      app_project_dir: '**/app',
      flavor: 'internal'
    )
    UI.message("Current version: #{cur_build}")
    arr_build = cur_build.split(".")
    patch_build = arr_build[index].to_i + 1
    arr_build[index] = patch_build.to_s 
    # Reset other version
    if index == 0
      arr_build[1] = "0"
      arr_build[2] = "0"
    elsif index == 1
      arr_build[2] = "0"
    end

    new_version = arr_build.join(".")
    UI.message("New ios version: #{new_version}")
    UI.message("Version '" + to_update + "' incremented")
  end

end




