# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

default_platform(:android)

# Ex: fastlane beta build_type:debug flavor_type:internal update:patch
platform :android do

  admitted = ["internal", "closed", "open"]

  desc "Submit a new Internal Draft Build to Play Store"
  lane :beta do |options|

    flavor_type = options[:flavor_type]

    if flavor_type == nil
      UI.user_error!("'flavor_type' parameter not present")
      # UI.important "Skipping build because a cached build is available!"
      # next # skip doing the rest of this lane
    end

    if !admitted.include?(flavor_type)
      UI.user_error!("'" + flavor_type + "' must be one of: 'internal', 'closed', 'open'")
    end
    UI.message("Build type present and correct: #{flavor_type}")


    admitted_bump = ["major", "minor", "patch"]
    to_update = options[:update]

    if to_update == nil
      UI.user_error!("'update' parameter not present")
      # UI.important "Skipping build because a cached build is available!"
      # next # skip doing the rest of this lane
    end

    if !admitted_bump.include?(to_update)
      UI.user_error!("'" + to_update + "' must be one of: 'minor', 'major', 'patch'")
    end
    UI.message("to_update present and correct: #{to_update}")


    gradle(task: 'clean')
    UI.message("Gradle clean success")

    Increment version
    version_name = increment_version_name(
      app_project_dir: '**/app',
      bump_type: to_update,
      flavor: flavor_type
    )
    UI.message("New version name: #{version_name}")

    version_code = increment_version_code(app_project_dir: '**/app', flavor: flavor_type)
    UI.message("New version code: #{version_code}")

    gradle(
      # task: 'assemble',
      task: 'bundle',
      flavor: flavor_type,
      build_type: 'Release',     
      print_command: false
    )
    UI.message("Gradle bundle succeded")


    git_commit(path: "..", message: "Version Bump")
    push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "master",  # optional, aliased by "branch", default is set to current branch
      remote_branch: "master"
    )
    UI.message("Branch updated")

    upload_to_play_store(
      track: flavor_type,
      release_status: 'draft',
      version_name: version_name
    )
    UI.message("Deploy succesfull")
  end
end




# TESTING
lane :show_version do
  # Default
  version = get_version_name(app_project_dir: '**/app')
  UI.message("Default: #{version}")
  version_code = get_version_code(app_project_dir: '**/app')
  UI.message("Default: #{version_code}")

  # Demo
  version_demo = get_version_name(
    app_project_dir: '**/app',
    flavor: 'demo'
  )
  UI.message("demo flavor: #{version_demo}")
  version_code_demo = get_version_code(
    app_project_dir: '**/app',
    flavor: 'demo'
  )
  UI.message("demo flavor: #{version_code_demo}")

  # Qa
  version_qa = get_version_name(
    app_project_dir: '**/app',
    flavor: 'qa'
  )
  UI.message("qa flavor: #{version_qa}")
  version_code_qa = get_version_code(
    app_project_dir: '**/app',
    flavor: 'qa'
  )
  UI.message("qa flavor: #{version_code_qa}")
end

#major minor patch build
lane :bumpup do
  # Default
  increment_version_name(app_project_dir: '**/app', bump_type: 'patch')
  increment_version_code(app_project_dir: '**/app')

  #internal
  # increment_version_name(
  #   app_project_dir: '**/app',
  #   bump_type: 'patch',
  #   flavor: 'internal'
  # )
  # increment_version_code(app_project_dir: '**/app', flavor: "internal")

  # #Qa
  # increment_version_name(
  #   app_project_dir: '**/app',
  #   bump_type: 'patch',
  #   flavor: 'internal'
  # )
  # increment_version_code(app_project_dir: '**/app', flavor: "internal")

  git_commit(path: "..", message: "Version Bump")
  push_to_git_remote(
    remote: "origin",         # optional, default: "origin"
    local_branch: "master",  # optional, aliased by "branch", default is set to current branch
    remote_branch: "master"
  )

end